before:
  hooks:
  - make man-page

builds:
  -
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    - windows
    goarch:
    - 386
    - amd64
    - arm
    - arm64
    goarm:
    - 6
    - 7
    ignore:
    - goos: darwin
      goarch: 386
    - goos: darwin
      goarch: arm

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

archives:
  -
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
    files:
    - LICENSE
    - README.md
    - docs/*.md
      # man-pages is also defined in Makefile
    - docs/man-pages/man1/*

brews:
  -
    tap:
      owner: meyermarcel
      name: homebrew-tap
    folder: Formula
    description: "Generate or validate intermodal container markings."
    homepage: "https://github.com/meyermarcel/icm"
    install: |
      bin.install "icm"

      # Install bash completion
      bash_output = Utils.popen_read("#{bin}/icm completion bash")
      (bash_completion/"icm").write bash_output

      # Install zsh completion
      zsh_output = Utils.popen_read("#{bin}/icm completion zsh")
      (zsh_completion/"_icm").write zsh_output

      # Install fish completion
      fish_output = Utils.popen_read("#{bin}/icm completion fish")
      (fish_completion/"icm.fish").write fish_output

      # man-pages is also defined in Makefile
      man1.install Dir["docs/man-pages/man1/*.1"]

    test: |
      system "#{bin}/icm --version"

scoop:
  bucket:
    owner: meyermarcel
    name: scoop-bucket
  homepage: "https://github.com/meyermarcel/icm"
  description: "Generate or validate intermodal container markings."
  license: MIT
