language: go
go:
- "1.11.x"

env:
- CGO_ENABLED=0

before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- go get -u github.com/alecthomas/gometalinter
- gometalinter --install

script:
- make

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

notifications:
  email: false
