language: go
go:
- "1.10.3"

before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- go get -u github.com/alecthomas/gometalinter
- gometalinter --install

script:
- make

notifications:
  email: false
