# Config
#
#  Separators
#
#  ABC U 123456 0   20 G1
#     ↑ ↑      ↑  ↑   ↑
#     │ │      │  │   └─ sep-size-type
#     │ │      │  │
#     │ │      │  └─ sep-check-size
#     │ │      │
#     │ │      └─ sep-serial-check
#     │ │
#     │ └─ sep-equip-serial
#     │
#     └─ sep-owner-equip
#
sep-owner-equip: ''
sep-equip-serial: ' '
sep-serial-check: '-'
sep-check-size: ', '
sep-size-type: ' '
