name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Init dummy owners CSV
        run: make dummy-csv

      - name: Audit dependencies
        run: make audit

      - name: Go mod tidy
        run: go mod tidy -diff

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Require: The version of golangci-lint to use.
          version: latest

      - name: Test and build
        run: make test build
