name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:

  goreleaser:
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          # https://github.com/goreleaser/goreleaser/issues/982
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
