name: goreleaser

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  goreleaser:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Generate manpage and download owners CSV
        # download-owners must be the last executed target if not dummy CSV will be embedded instead.
        run: make man-page download-owners

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          # https://github.com/goreleaser/goreleaser/issues/982
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
